### Hello
GET http://localhost:3000

### aluno
POST http://localhost:3000/alunos
Content-Type: application/json

{
  "nome": "John",
  "endereco": "Doe",
  "telefone": "12345612",
  "email": "email@email.com",
  "idade": 17
}